// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestaoCinco.Infra.Data.Context;

#nullable disable

namespace QuestaoCinco.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240229183857_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuestaoCinco.Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<string>("ContaId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomeTitular")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("SaldoAtual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ValorInicial")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ContaId");

                    b.ToTable("ContasCorrente");
                });

            modelBuilder.Entity("QuestaoCinco.Domain.Entities.Lancamento", b =>
                {
                    b.Property<int>("LancamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LancamentoId"));

                    b.Property<string>("ContaId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("datetime");

                    b.Property<string>("DebitoCredito")
                        .HasColumnType("char(1)");

                    b.Property<decimal>("SaldoAntes")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SaldoApos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("LancamentoId");

                    b.HasIndex("ContaId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("QuestaoCinco.Domain.Entities.Lancamento", b =>
                {
                    b.HasOne("QuestaoCinco.Domain.Entities.ContaCorrente", null)
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaId");
                });

            modelBuilder.Entity("QuestaoCinco.Domain.Entities.ContaCorrente", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
